break check major version certify (#1522)

diff --git a/.github/workflows/semver.yml b/.github/workflows/semver.yml
--- a/.github/workflows/semver.yml
+++ b/.github/workflows/semver.yml
@@ -59,22 +59,32 @@ jobs:
         id: break-check
         run: |
           set +e
-          bun ./packages/break-check/src/break-check.x.ts \
+          result=$(bun ./packages/break-check/src/break-check.x.ts \
             --tagPattern="atom.io" \
             --testPattern="packages/atom.io/__tests__/public/**/*.test.{ts,tsx}" \
-            --testCommand="cd packages/atom.io && bun run build && bun run test:once:public"
+            --testCommand="(cd packages/atom.io && bun run build && bun run test:once:public)" \
+            --certifyCommand="grep -q -F '"atom.io": major' .changeset/*.md"
+          )
           case $? in
             0)
-              echo "atom.io=✅ No public tests from the last release broke." >> $GITHUB_OUTPUT
+              # if result includes "breaking-changes-certified"
+              if [[ $result == *"breaking-changes-certified"* ]]; then
+                echo "atom.io=⚠️ Public tests from the last release broke, and a new major version has been certified." >> $GITHUB_OUTPUT
+              else 
+                echo "atom.io=✅ No public tests from the last release broke." >> $GITHUB_OUTPUT
+              fi
               ;;
             1)
-              echo "atom.io=⚠️ Public tests from the last release are breaking." >> $GITHUB_OUTPUT
+              echo "atom.io=❌ Public tests from the last release are breaking." >> $GITHUB_OUTPUT
+              echo "failed=true" >> $GITHUB_OUTPUT
               ;;
             2)
-              echo "atom.io=❌ No tests were found matching the pattern." >> $GITHUB_OUTPUT
+              echo "atom.io=❌ No tests were found matching the `--testPattern` provided." >> $GITHUB_OUTPUT
+              echo "failed=true" >> $GITHUB_OUTPUT
               ;;
             *)
               echo "Error: The command failed with an unexpected exit code: $exit_code."
+              echo "failed=true" >> $GITHUB_OUTPUT
               ;;
           esac
           set -e
@@ -96,3 +106,9 @@ jobs:
             ## break-check
             ${{ steps.break-check.outputs['atom.io'] }}
           edit-mode: replace
+
+      - name: Pass/Fail
+        if: ${{ steps.break-check.outputs.failed == 'true' }}
+        run: |
+          echo "Breaking changes were detected. Please fix them before merging."
+          exit 1
